export { PaginaCatalogar } from './PaginaCatalogar'
export { PaginaPlanos } from './PaginaPlanos'
export { PaginaModeracao } from './PaginaModeracao'
export { PaginaEscrever } from './PaginaEscrever'
export { PaginaPessoasAdmin } from './PaginaPessoasAdmin'
export { PaginaVocabulario } from './PaginaVocabulario'
