// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SaraivaTech.Planoteca.Infra.Data.Context;

#nullable disable

namespace SaraivaTech.Planoteca.Infra.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260822181410_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SaraivaTech.Planoteca.Domain.Entities.Bncc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("codigo");

                    b.Property<Guid>("PlanoId")
                        .HasColumnType("uuid")
                        .HasColumnName("plano_id");

                    b.HasKey("Id")
                        .HasName("pk_bncc");

                    b.HasIndex("PlanoId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_bncc_plano_id_codigo");

                    b.ToTable("bncc", (string)null);
                });

            modelBuilder.Entity("SaraivaTech.Planoteca.Domain.Entities.Componente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("area");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cor");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("varchar(2)")
                        .HasColumnName("sigla");

                    b.HasKey("Id")
                        .HasName("pk_componente");

                    b.ToTable("componente", (string)null);
                });

            modelBuilder.Entity("SaraivaTech.Planoteca.Domain.Entities.EtapaPlano", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<Guid>("PlanoId")
                        .HasColumnType("uuid")
                        .HasColumnName("plano_id");

                    b.Property<string>("Titulo")
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("pk_etapa_plano");

                    b.HasIndex("PlanoId", "Ordem")
                        .IsUnique()
                        .HasDatabaseName("ix_etapa_plano_plano_id_ordem");

                    b.ToTable("etapa_plano", (string)null);
                });

            modelBuilder.Entity("SaraivaTech.Planoteca.Domain.Entities.Metodologia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativa");

                    b.Property<string>("Fonte")
                        .HasColumnType("text")
                        .HasColumnName("fonte");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_metodologia");

                    b.ToTable("metodologia", (string)null);
                });

            modelBuilder.Entity("SaraivaTech.Planoteca.Domain.Entities.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("GoogleSub")
                        .HasColumnType("text")
                        .HasColumnName("google_sub");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("papel");

                    b.HasKey("Id")
                        .HasName("pk_pessoa");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_pessoa_email");

                    b.HasIndex("GoogleSub")
                        .IsUnique()
                        .HasDatabaseName("ix_pessoa_google_sub");

                    b.ToTable("pessoa", (string)null);
                });

            modelBuilder.Entity("SaraivaTech.Planoteca.Domain.Entities.Plano", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArquivoUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("arquivo_url");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Autoria")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("autoria");

                    b.Property<Guid?>("CatalogadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalogado_por_id");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("DuracaoAulas")
                        .HasColumnType("integer")
                        .HasColumnName("duracao_aulas");

                    b.Property<string>("DuracaoDescricao")
                        .HasColumnType("text")
                        .HasColumnName("duracao_descricao");

                    b.Property<string>("ExpectativasAprendizagem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("expectativas_aprendizagem");

                    b.Property<string>("LinksExtras")
                        .HasColumnType("jsonb")
                        .HasColumnName("links_extras");

                    b.Property<string>("Modalidade")
                        .HasColumnType("text")
                        .HasColumnName("modalidade");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("objetivo");

                    b.Property<string>("ObjetosConhecimento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("objetos_conhecimento");

                    b.Property<DateTime?>("PublicadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publicado_em");

                    b.Property<string>("Recursos")
                        .HasColumnType("text")
                        .HasColumnName("recursos");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("situacao");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.Property<string>("TurmaOrigem")
                        .HasColumnType("text")
                        .HasColumnName("turma_origem");

                    b.HasKey("Id")
                        .HasName("pk_plano");

                    b.HasIndex("CatalogadoPorId")
                        .HasDatabaseName("ix_plano_catalogado_por_id");

                    b.HasIndex("Situacao")
                        .HasDatabaseName("ix_plano_situacao");

                    b.ToTable("plano", (string)null);
                });

            modelBuilder.Entity("SaraivaTech.Planoteca.Domain.Entities.PlanoComponente", b =>
                {
                    b.Property<Guid>("PlanoId")
                        .HasColumnType("uuid")
                        .HasColumnName("plano_id");

                    b.Property<Guid>("ComponenteId")
                        .HasColumnType("uuid")
                        .HasColumnName("componente_id");

                    b.Property<bool>("EPrincipal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("e_principal");

                    b.HasKey("PlanoId", "ComponenteId")
                        .HasName("pk_plano_componente");

                    b.HasIndex("ComponenteId")
                        .HasDatabaseName("ix_plano_componente_componente_id");

                    b.ToTable("plano_componente", (string)null);
                });

            modelBuilder.Entity("SaraivaTech.Planoteca.Domain.Entities.PlanoMetodologia", b =>
                {
                    b.Property<Guid>("PlanoId")
                        .HasColumnType("uuid")
                        .HasColumnName("plano_id");

                    b.Property<Guid>("MetodologiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("metodologia_id");

                    b.HasKey("PlanoId", "MetodologiaId")
                        .HasName("pk_plano_metodologia");

                    b.HasIndex("MetodologiaId")
                        .HasDatabaseName("ix_plano_metodologia_metodologia_id");

                    b.ToTable("plano_metodologia", (string)null);
                });

            modelBuilder.Entity("SaraivaTech.Planoteca.Domain.Entities.PlanoSerie", b =>
                {
                    b.Property<Guid>("PlanoId")
                        .HasColumnType("uuid")
                        .HasColumnName("plano_id");

                    b.Property<Guid>("SerieId")
                        .HasColumnType("uuid")
                        .HasColumnName("serie_id");

                    b.HasKey("PlanoId", "SerieId")
                        .HasName("pk_plano_serie");

                    b.HasIndex("SerieId")
                        .HasDatabaseName("ix_plano_serie_serie_id");

                    b.ToTable("plano_serie", (string)null);
                });

            modelBuilder.Entity("SaraivaTech.Planoteca.Domain.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("autor_id");

                    b.Property<string>("ComentarioModeracao")
                        .HasColumnType("text")
                        .HasColumnName("comentario_moderacao");

                    b.Property<string>("Corpo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("corpo");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("ModeradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("moderado_em");

                    b.Property<Guid?>("ModeradoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("moderado_por_id");

                    b.Property<DateTime?>("PublicadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publicado_em");

                    b.Property<string>("Resumo")
                        .HasColumnType("text")
                        .HasColumnName("resumo");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("situacao");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("pk_post");

                    b.HasIndex("AutorId")
                        .HasDatabaseName("ix_post_autor_id");

                    b.HasIndex("ModeradoPorId")
                        .HasDatabaseName("ix_post_moderado_por_id");

                    b.HasIndex("Situacao")
                        .HasDatabaseName("ix_post_situacao");

                    b.ToTable("post", (string)null);
                });

            modelBuilder.Entity("SaraivaTech.Planoteca.Domain.Entities.Serie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativa");

                    b.Property<string>("Etapa")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("etapa");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<string>("RotuloCompleto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rotulo_completo");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sigla");

                    b.HasKey("Id")
                        .HasName("pk_serie");

                    b.HasIndex("Ordem")
                        .IsUnique()
                        .HasDatabaseName("ix_serie_ordem");

                    b.HasIndex("Etapa", "Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_serie_etapa_nome");

                    b.ToTable("serie", (string)null);
                });

            modelBuilder.Entity("SaraivaTech.Planoteca.Domain.Entities.Bncc", b =>
                {
                    b.HasOne("SaraivaTech.Planoteca.Domain.Entities.Plano", "Plano")
                        .WithMany("CodigosBncc")
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bncc_plano_plano_id");

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("SaraivaTech.Planoteca.Domain.Entities.EtapaPlano", b =>
                {
                    b.HasOne("SaraivaTech.Planoteca.Domain.Entities.Plano", "Plano")
                        .WithMany("Etapas")
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_etapa_plano_plano_plano_id");

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("SaraivaTech.Planoteca.Domain.Entities.Plano", b =>
                {
                    b.HasOne("SaraivaTech.Planoteca.Domain.Entities.Pessoa", "CatalogadoPor")
                        .WithMany()
                        .HasForeignKey("CatalogadoPorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_plano_pessoa_catalogado_por_id");

                    b.Navigation("CatalogadoPor");
                });

            modelBuilder.Entity("SaraivaTech.Planoteca.Domain.Entities.PlanoComponente", b =>
                {
                    b.HasOne("SaraivaTech.Planoteca.Domain.Entities.Componente", "Componente")
                        .WithMany()
                        .HasForeignKey("ComponenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plano_componente_componente_componente_id");

                    b.HasOne("SaraivaTech.Planoteca.Domain.Entities.Plano", "Plano")
                        .WithMany("Componentes")
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plano_componente_plano_plano_id");

                    b.Navigation("Componente");

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("SaraivaTech.Planoteca.Domain.Entities.PlanoMetodologia", b =>
                {
                    b.HasOne("SaraivaTech.Planoteca.Domain.Entities.Metodologia", "Metodologia")
                        .WithMany()
                        .HasForeignKey("MetodologiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plano_metodologia_metodologia_metodologia_id");

                    b.HasOne("SaraivaTech.Planoteca.Domain.Entities.Plano", "Plano")
                        .WithMany("Metodologias")
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plano_metodologia_plano_plano_id");

                    b.Navigation("Metodologia");

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("SaraivaTech.Planoteca.Domain.Entities.PlanoSerie", b =>
                {
                    b.HasOne("SaraivaTech.Planoteca.Domain.Entities.Plano", "Plano")
                        .WithMany("Series")
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plano_serie_plano_plano_id");

                    b.HasOne("SaraivaTech.Planoteca.Domain.Entities.Serie", "Serie")
                        .WithMany()
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plano_serie_serie_serie_id");

                    b.Navigation("Plano");

                    b.Navigation("Serie");
                });

            modelBuilder.Entity("SaraivaTech.Planoteca.Domain.Entities.Post", b =>
                {
                    b.HasOne("SaraivaTech.Planoteca.Domain.Entities.Pessoa", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_post_pessoa_autor_id");

                    b.HasOne("SaraivaTech.Planoteca.Domain.Entities.Pessoa", "ModeradoPor")
                        .WithMany()
                        .HasForeignKey("ModeradoPorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_post_pessoa_moderado_por_id");

                    b.Navigation("Autor");

                    b.Navigation("ModeradoPor");
                });

            modelBuilder.Entity("SaraivaTech.Planoteca.Domain.Entities.Plano", b =>
                {
                    b.Navigation("CodigosBncc");

                    b.Navigation("Componentes");

                    b.Navigation("Etapas");

                    b.Navigation("Metodologias");

                    b.Navigation("Series");
                });
#pragma warning restore 612, 618
        }
    }
}
