export type { Conta, Papel } from './modelo'
export { DESCRICAO_PAPEL, PAPEIS_CONTA, ROTULO_PAPEL, primeiroNomeDe } from './modelo'
export type { FiltroConta } from './api'
export { alterarAtivo, alterarPapel, listarContas } from './api'
export { CHAVE_CONTAS, useAlterarAtivo, useAlterarPapel, useContas } from './useContas'
